language: android
android:
    components:
        - build-tools-26.0.2
        - android-26
        - add-on
        - extra
    licenses:
        - 'build-tools;28.0.3.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
        - 'platforms;android-28.+'
